services:

  frontend:
    build: ./frontend
    ports:
      - "3091:3000"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - "8091:8000"
    volumes:
      - ./backend/storage:/app/storage
      - ./backend/utils:/app/utils
    restart: unless-stopped
